{
  imports = [
    ./fusion.nix
    #./dashy.nix
    ./kavita.nix
    ./tachidesk.nix
    ./morphos.nix
    ./searxng.nix
    ./technitium-dns.nix
    ./qbittorrent.nix
    ./it-tools.nix
    ./wallos.nix
    ./stirling-pdf.nix
    ./omni-tools.nix
    ./mazanoke.nix
    ./local-content-share.nix
    ./flame-homepage.nix
    ./vikunja.nix
    ./local-voice
  ];
}