{ pkgs, ... }:
{
  home.packages = with pkgs; [
    spotify
    vesktop
    telegram-desktop
    jellyfin-desktop
    obsidian
    chromium
    tenacity
    bitwarden-desktop
    blueman
    rofi-network-manager
    caligula
    libreoffice-fresh
    vlc
    mission-center
    element-desktop
    papers
    loupe
    gnome-calendar
    gnome-calculator
    kenku-fm
    jetbrains.rider
    wonderdraft
    kdePackages.kate
    kdePackages.kdenlive
  ];
}
